# browser-skill 本机安装（Windows）
# 用法: powershell -ExecutionPolicy Bypass -File install.ps1

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$SkillDir = Join-Path $env:USERPROFILE ".pi\agent\skills\browser"
$BinDir = Join-Path $env:USERPROFILE "bin"
$BinShim = Join-Path $BinDir "browser"

Write-Host "=== browser-skill install ===" -ForegroundColor Cyan
Write-Host "Source: $Root"

# 1) deps
Write-Host "`n[1/4] Python packages ..." -ForegroundColor Yellow
python -m pip install -r (Join-Path $Root "requirements.txt")
if ($LASTEXITCODE -ne 0) { throw "pip install failed" }

Write-Host "`n[2/4] Playwright chromium ..." -ForegroundColor Yellow
python -m playwright install chromium
if ($LASTEXITCODE -ne 0) { Write-Host "  warn: playwright install failed; run later: python -m playwright install chromium" -ForegroundColor DarkYellow }

# 2) skill copy/link
Write-Host "`n[3/4] Install skill -> $SkillDir ..." -ForegroundColor Yellow
$parent = Split-Path $SkillDir -Parent
if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }

if ((Resolve-Path $Root).Path -eq (if (Test-Path $SkillDir) { (Resolve-Path $SkillDir).Path } else { "" })) {
    Write-Host "  already running from skill dir, skip copy"
} else {
    if (Test-Path $SkillDir) {
        Write-Host "  target exists; overlay copy (keeps local config outside skill)"
    } else {
        New-Item -ItemType Directory -Force -Path $SkillDir | Out-Null
    }
    Copy-Item -Path (Join-Path $Root "*") -Destination $SkillDir -Recurse -Force -Exclude @(".git", ".pytest_cache", "__pycache__")
    Write-Host "  copied"
}

# 3) PATH shim
Write-Host "`n[4/4] CLI shim -> $BinShim ..." -ForegroundColor Yellow
if (-not (Test-Path $BinDir)) { New-Item -ItemType Directory -Force -Path $BinDir | Out-Null }
$daemon = (Join-Path $SkillDir "browser_daemon.py") -replace "\\", "/"
@(
    "#!/usr/bin/env bash",
    "# auto-generated by browser-skill install.ps1",
    "python -X utf8 `"$daemon`" `"$@`""
) | Set-Content -Path $BinShim -Encoding utf8NoBOM
# also write .cmd for cmd.exe
$cmd = Join-Path $BinDir "browser.cmd"
"@echo off`r`npython -X utf8 `"$SkillDir\browser_daemon.py`" %*" | Set-Content -Path $cmd -Encoding ascii

Write-Host "`n=== done ===" -ForegroundColor Green
Write-Host "Add to PATH if needed: $BinDir"
Write-Host "Try:"
Write-Host "  browser status"
Write-Host "  browser read_url https://example.com"
Write-Host "  pytest tests/ -q   (from skill dir)"
