#!/usr/bin/env bash
# browser-skill local install (Git Bash / Linux / macOS)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="${HOME}/.pi/agent/skills/browser"
BIN_DIR="${HOME}/bin"
BIN_SHIM="${BIN_DIR}/browser"

echo "=== browser-skill install ==="
echo "Source: $ROOT"

echo
echo "[1/4] Python packages ..."
python -m pip install -r "$ROOT/requirements.txt"

echo
echo "[2/4] Playwright chromium ..."
python -m playwright install chromium || echo "warn: playwright install failed; run later: python -m playwright install chromium"

echo
echo "[3/4] Install skill -> $SKILL_DIR ..."
mkdir -p "$(dirname "$SKILL_DIR")"
if [ "$(cd "$ROOT" && pwd)" = "$(cd "$SKILL_DIR" 2>/dev/null && pwd)" ]; then
  echo "  already running from skill dir, skip copy"
else
  mkdir -p "$SKILL_DIR"
  # rsync if available, else cp
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --exclude '.git' --exclude '.pytest_cache' --exclude '__pycache__' "$ROOT/" "$SKILL_DIR/"
  else
    cp -R "$ROOT/." "$SKILL_DIR/"
    rm -rf "$SKILL_DIR/.git" "$SKILL_DIR/.pytest_cache" 2>/dev/null || true
  fi
  echo "  copied"
fi

echo
echo "[4/4] CLI shim -> $BIN_SHIM ..."
mkdir -p "$BIN_DIR"
DAEMON="$SKILL_DIR/browser_daemon.py"
cat > "$BIN_SHIM" <<EOF
#!/usr/bin/env bash
# auto-generated by browser-skill install.sh
exec python -X utf8 "$DAEMON" "\$@"
EOF
chmod +x "$BIN_SHIM" "$SKILL_DIR/bin/browser" 2>/dev/null || true

echo
echo "=== done ==="
echo "Ensure $BIN_DIR is on PATH"
echo "Try:"
echo "  browser status"
echo "  browser read_url https://example.com"
echo "  pytest tests/ -q   (from skill dir)"
